// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzYXwbrl8E8As2iUYTsQc7I3WgRWYBPIk',
    appId: '1:661137830460:web:e4e5a26c87b6ea8de14939',
    messagingSenderId: '661137830460',
    projectId: 'notas-marti-75827',
    authDomain: 'notas-marti-75827.firebaseapp.com',
    storageBucket: 'notas-marti-75827.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfKBW2BVzQBTOSYdySgVUx4Q4k9wpoCjY',
    appId: '1:661137830460:android:47a0b0cf71ca9b0fe14939',
    messagingSenderId: '661137830460',
    projectId: 'notas-marti-75827',
    storageBucket: 'notas-marti-75827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW9GoB1Jl7zZSYfCsURcYdD_O5ulvCeWk',
    appId: '1:661137830460:ios:6fc766a54d7b9aefe14939',
    messagingSenderId: '661137830460',
    projectId: 'notas-marti-75827',
    storageBucket: 'notas-marti-75827.firebasestorage.app',
    iosBundleId: 'com.example.martiNotas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW9GoB1Jl7zZSYfCsURcYdD_O5ulvCeWk',
    appId: '1:661137830460:ios:6fc766a54d7b9aefe14939',
    messagingSenderId: '661137830460',
    projectId: 'notas-marti-75827',
    storageBucket: 'notas-marti-75827.firebasestorage.app',
    iosBundleId: 'com.example.martiNotas',
  );
}
