// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGazsDLo6VJeXNag08o3hpQZOHk33jpg4',
    appId: '1:840977230887:web:24a239718e71eaab7b7202',
    messagingSenderId: '840977230887',
    projectId: 'app-notas-3d555',
    authDomain: 'app-notas-3d555.firebaseapp.com',
    storageBucket: 'app-notas-3d555.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfntMQubEaWJhTAWw0Y-0uvPuB_BmpOw',
    appId: '1:840977230887:android:da10f9906a9c699e7b7202',
    messagingSenderId: '840977230887',
    projectId: 'app-notas-3d555',
    storageBucket: 'app-notas-3d555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Tf24tJ9U86CSqwNQmhQUgFVOzmmIQVk',
    appId: '1:840977230887:ios:d86913c7dd346bb77b7202',
    messagingSenderId: '840977230887',
    projectId: 'app-notas-3d555',
    storageBucket: 'app-notas-3d555.firebasestorage.app',
    iosBundleId: 'com.example.martiNotas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Tf24tJ9U86CSqwNQmhQUgFVOzmmIQVk',
    appId: '1:840977230887:ios:d86913c7dd346bb77b7202',
    messagingSenderId: '840977230887',
    projectId: 'app-notas-3d555',
    storageBucket: 'app-notas-3d555.firebasestorage.app',
    iosBundleId: 'com.example.martiNotas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGazsDLo6VJeXNag08o3hpQZOHk33jpg4',
    appId: '1:840977230887:web:548674dfb2764e0b7b7202',
    messagingSenderId: '840977230887',
    projectId: 'app-notas-3d555',
    authDomain: 'app-notas-3d555.firebaseapp.com',
    storageBucket: 'app-notas-3d555.firebasestorage.app',
  );

}